/**
 * This module contains definitions of **The Binary Protocol**.
 *
 * ## The Binary Protocol
 *
 * ### Packet
 * |Offset|Type |Description|
 * |------|-----|-----------|
 * |+0    |uint8|Packet type|
 * |+1    |data |Packet data|
 *
 * @see {@linkcode PacketType}
 */

/** */
export enum PacketType {
  /**
   * #### `HANDSHAKE` packet (`0x00`)
   * This is a **server packet**.
   *
   * |Offset|Type |Description                                               |
   * |------|-----|----------------------------------------------------------|
   * |+0    |uint8|Packet type                                               |
   * |+1    |uint8|Client ID (generated by the server and **must be unique**)|
   */
  HANDSHAKE,
  /**
   * #### `ADD_DEVICE` packet (`0x01`)
   * This is a **client packet**.
   *
   * |Offset|Type |Description                                              |
   * |------|-----|---------------------------------------------------------|
   * |+0    |uint8|Packet type                                              |
   * |+1    |uint8|Device type                                              |
   * |+2    |uint8|Device ID (generated by the client and **must be unique**|
   *
   * @see [`DEVICE_TYPES`](../modules/_gluenet_device_.html#device_types)
   */
  ADD_DEVICE,
  /**
   * #### `REMOVE_DEVICE` packet (`0x02`)
   * This is a **client packet**.
   *
   * |Offset|Type |Description                                              |
   * |------|-----|---------------------------------------------------------|
   * |+0    |uint8|Packet type                                              |
   * |+1    |uint8|Device ID (generated by the client and **must be unique**|
   */
  REMOVE_DEVICE,
  /**
   * #### `EVENT` packet (`0x03`)
   * This is a **client packet**.
   *
   * |Offset|Type   |Description|
   * |------|-------|-----------|
   * |+0    |uint8  |Packet type|
   * |+1    |uint8  |Device ID  |
   * |+2    |uint8  |Event ID   |
   * |+3    |uint8[]|Event data |
   */
  EVENT,
  /**
   * #### `COMMAND` packet (`0x04`)
   * This is a **server packet**.
   *
   * |Offset|Type   |Description |
   * |------|-------|------------|
   * |+0    |uint8  |Packet type |
   * |+1    |uint8  |Device ID   |
   * |+2    |uint8  |Command ID  |
   * |+3    |uint8[]|Command data|
   */
  COMMAND
}
